/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import logic.logica;

/**
 *
 * @author EILEMUS
 */
public class regresionDataView extends javax.swing.JFrame {

    /**
     * Creates new form regresionDataView
     */
    logica log;
    DefaultTableModel modelo = new DefaultTableModel();
    int iy;
    int ix[];
    double[][] matrizX;
    double[][] matrizY;
    String result;
    
    public regresionDataView() {
        iy=0;
        log = logica.getLogica();
        result="";
        ix = new int[log.getMatrizX().length];
        for(int i=0;i<log.getMatrizY().length;i++){
        ix[i]=0;
        }
        modelo.addColumn("Y");
        initComponents();
        for(int i=0; i<log.getMatrizX()[0].length-1;i++){
        selectorX.addItem("X"+(i+1));
        modelo.addColumn("X"+(i+1));
        }
        modelo.setRowCount(log.getMatrizY().length);
        tabla.setModel(modelo);
        tabla.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        matrizXin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        matrizYin = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        selectorX = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Regresión lineal Multiple");

        jLabel2.setText("Y");

        jLabel3.setText("para:");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        jButton3.setText("Calcular");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Limpiar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Limpiar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(matrizYin, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(97, 97, 97)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(selectorX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(matrizXin, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(matrizYin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton5))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(matrizXin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(selectorX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        try{
        log.addMatrizY( Double.parseDouble(matrizYin.getText()));
        matrizY= log.getMatrizY();
        modelo.setValueAt(matrizYin.getText(),iy, 0);
        iy++;
        matrizYin.setText("");
        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try{
        log.addMatrizX( ix[selectorX.getSelectedIndex()],selectorX.getSelectedIndex()+1 ,Double.parseDouble(matrizXin.getText()));
         matrizX = log.getMatrizX();
        System.out.println("----matriz X----");
        for(int i = 0; i < matrizX.length; i++){
            for(int j = 0; j < matrizX[i].length; j++){
                System.out.print(matrizX[i][j]+"  ");
            }
            System.out.println("");
        }
        modelo.setValueAt(matrizXin.getText(),ix[selectorX.getSelectedIndex()], selectorX.getSelectedIndex()+1);
        ix[selectorX.getSelectedIndex()]++;
        matrizXin.setText("");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        double trMatriz[][] = log.transpuesta(matrizX);       
        double[][] XX = log.multiplicarMatrices(trMatriz,matrizX);
        double[][] inversa = log.matrizInversa(XX);
        double[][] xTY = log.multiplicarMatrices(trMatriz,matrizY);
        double[][] beta= log.multiplicarMatrices(inversa,xTY);
        double betaTranspuesta[][] = log.transpuesta(beta);
        double[][] bXY = log.multiplicarMatrices(betaTranspuesta, xTY);
            
        
        result+="----matriz Y---- \n";
        for(int i = 0; i < matrizY.length; i++){
            for(int j = 0; j < matrizY[i].length; j++){
                result+=String.valueOf(matrizY[i][j]+"  ");
            }
            result+="\n";
        }
        
        result+="----matriz X---- (metodo matricial: agrega columna de valor 1) \n";
        for(int i = 0; i < matrizX.length; i++){
            for(int j = 0; j < matrizX[i].length; j++){
                result+=String.valueOf(matrizX[i][j]+"  ");
            }
            result+="\n";
        }
        
        
        result+="----X transpuesta---- \n";
        for(int i = 0; i < trMatriz.length; i++){
            for(int j = 0; j < trMatriz[i].length; j++){
               result+=String.valueOf(trMatriz[i][j]+"  ");
            }
            result+=("\n");
        }
        
        result+="------(X'X)------- \n";
        for(int i = 0; i < XX.length; i++){
            for(int j = 0; j < XX[i].length; j++){
                result+=String.valueOf(XX[i][j]+"  ");
            }
            result+="\n";
        }
        
        result+="***** (X'X)^-1 ***** \n";
        for(int i = 0; i < inversa.length; i++){
            for(int j = 0; j < inversa[i].length; j++){
                result+=String.valueOf(inversa[i][j]+"  ");
            }
            result+="\n";
        }
        
        result+="***** (X'y) *****\n";
        for(int i = 0; i < xTY.length; i++){
            for(int j = 0; j < xTY[i].length; j++){
                result+=String.valueOf(xTY[i][j]+"  ");
            }
            result+="\n";
        }
        result+="***** (beta) *****\n";
        for(int i = 0; i < beta.length; i++){
            for(int j = 0; j < beta[i].length; j++){
                result+=String.valueOf(beta[i][j]+"  ");
            }
            result+="\n";
        }
        result += "Modelo de regresion:";
        String modelo ="b = ";
        for(int i = 0; i < beta.length; i++){
            for(int j = 0; j < beta[i].length; j++){
                if(i==0){
                modelo+=String.valueOf(beta[i][j])+" ";
                }else{
                    if(beta[i][j]>0){
                    modelo+=" + "+String.valueOf(beta[i][j])+"(X"+(i)+")";
                    }else{
                    modelo+=String.valueOf(beta[i][j])+"(X"+(i)+")";
                    }
                }
            }
        }
        
        result+=" \n"+modelo;
        
        double ssr=0;
        double sst=0;
        double sumatoria=0;
        for(int i = 0; i < matrizY.length; i++){
            for(int j = 0; j < matrizY[i].length; j++){
                sumatoria +=matrizY[i][j];
            }
        }
        sumatoria = Math.pow(sumatoria,2)/matrizY.length;
        ssr = bXY[0][0] - sumatoria;
        double[][] ytranspuesta= logica.transpuesta(matrizY);
        double[][] yy = logica.multiplicarMatrices(ytranspuesta, matrizY);
        sst = yy[0][0] - sumatoria;
        
        double R2 = ssr/sst;
        
        
        result+="\n SSR :"+String.valueOf(ssr);
        result+="\n SSR :"+String.valueOf(sst);
        result+="\n R^2 :"+String.valueOf(R2);
        
        
        
        log.setResultado(result);
        resultadoView resultado = new resultadoView();
        resultado.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        for (int i=0;i<matrizY.length;i++){
            modelo.setValueAt("",i, 0);
        }
        log.limpiarMatrizY();
        iy=0;
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        for (int i=0;i<matrizX.length;i++){
            modelo.setValueAt("",i, selectorX.getSelectedIndex()+1);
        }
        log.limpiarMatrizX(selectorX.getSelectedIndex()+1);
        for (int i=0;i<ix.length;i++){
            ix[selectorX.getSelectedIndex()]=0;
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regresionDataView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regresionDataView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regresionDataView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regresionDataView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regresionDataView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField matrizXin;
    private javax.swing.JTextField matrizYin;
    private javax.swing.JComboBox<String> selectorX;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
